In [ ]:
import pandas as pd
import numpy as np

In [ ]:
vetor = [10,np.nan,1,9,np.nan,20,np.nan,14,2,20]
dataframe = pd.DataFrame({"valores":vetor})

In [ ]:
dataframe.head(10)

valores
0     10.0
1      NaN
2      1.0
3      9.0
4      NaN
5     20.0
6      NaN
7     14.0
8      2.0
9     20.0

In [ ]:
def troca_media(dataframe,coluna):
    media = dataframe[coluna].mean()
    valores_trocados = dataframe[coluna].fillna(media)

    return valores_trocados

In [ ]:
dataframe["valores_trocados"] = troca_media(dataframe,"valores")

In [ ]:
dataframe.describe()

valores  valores_trocados
count   7.000000         10.000000
mean   10.857143         10.857143
std     7.712081          6.296888
min     1.000000          1.000000
25%     5.500000          9.250000
50%    10.000000         10.857143
75%    17.000000         13.214286
max    20.000000         20.000000

In [ ]:
vetor2 = [10,np.nan,1,9,np.nan,20,np.nan,14,2,20]

dicionario2 = {"valores":vetor2}
dataframe = pd.DataFrame(dicionario2)

In [ ]:
dataframe.head(10)

valores
0     10.0
1      NaN
2      1.0
3      9.0
4      NaN
5     20.0
6      NaN
7     14.0
8      2.0
9     20.0

In [ ]:
def troca_mediana(dataframe,coluna):
    mediana = dataframe[coluna].median()
    valores_trocados = dataframe[coluna].fillna(mediana)

    return valores_trocados

In [ ]:
dataframe["valores_trocados"] = troca_mediana(dataframe,"valores")

In [ ]:
dataframe.describe()

valores  valores_trocados
count   7.000000         10.000000
mean   10.857143         10.600000
std     7.712081          6.310485
min     1.000000          1.000000
25%     5.500000          9.250000
50%    10.000000         10.000000
75%    17.000000         13.000000
max    20.000000         20.000000

# Projeto prático

In [ ]:
dataframe = pd.read_csv("titanic.csv")

In [ ]:
dataframe.shape

(418, 13)

In [ ]:
dataframe.isnull().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex             23
Age             86
SibSp            0
Parch           48
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
dataframe.isnull().mean()

Unnamed: 0     0.000000
PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.055024
Age            0.205742
SibSp          0.000000
Parch          0.114833
Ticket         0.000000
Fare           0.002392
Cabin          0.782297
Embarked       0.000000
dtype: float64

In [ ]:
dataframe.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch          float64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(dataframe.drop("Survived",axis=1),dataframe["Survived"],test_size=0.3,random_state=0)


In [ ]:
X_treino.head(10)

Unnamed: 0  PassengerId  Pclass  ...     Fare Cabin  Embarked
96           96          988       1  ...  78.8500   C46         S
381         381         1273       3  ...   7.8792   NaN         Q
89           89          981       2  ...  23.0000   NaN         S
233         233         1125       3  ...   7.8792   NaN         Q
191         191         1083       1  ...  26.0000   NaN         S
354         354         1246       3  ...  20.5750   NaN         S
253         253         1145       3  ...   9.3250   NaN         S
92           92          984       1  ...  52.0000   B71         S
240         240         1132       1  ...  27.7208   NaN         C
194         194         1086       2  ...  32.5000   NaN         S

[10 rows x 12 columns]

In [ ]:
y_treino.head(10)

96     1
381    0
89     0
233    0
191    0
354    1
253    0
92     1
240    1
194    0
Name: Survived, dtype: int64

In [ ]:
X_teste.head(10)

Unnamed: 0  PassengerId  Pclass  ...     Fare Cabin  Embarked
360         360         1252       3  ...  69.5500   NaN         S
170         170         1062       3  ...   7.5500   NaN         S
224         224         1116       1  ...  27.4458   NaN         C
358         358         1250       3  ...   7.7500   NaN         Q
309         309         1201       3  ...  14.1083   NaN         S
308         308         1200       1  ...  93.5000   B69         S
150         150         1042       1  ...  83.1583   C54         C
10           10          902       3  ...   7.8958   NaN         S
21           21          913       3  ...   3.1708   NaN         S
261         261         1153       3  ...   7.8542   NaN         S

[10 rows x 12 columns]

In [ ]:
X_treino.shape

(292, 12)

In [ ]:
X_teste.shape

(126, 12)

In [ ]:
X_treino.drop(columns=["Unnamed: 0"], inplace=True)
X_teste.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
X_treino.head(10)

PassengerId  Pclass  ... Cabin Embarked
96           988       1  ...   C46        S
381         1273       3  ...   NaN        Q
89           981       2  ...   NaN        S
233         1125       3  ...   NaN        Q
191         1083       1  ...   NaN        S
354         1246       3  ...   NaN        S
253         1145       3  ...   NaN        S
92           984       1  ...   B71        S
240         1132       1  ...   NaN        C
194         1086       2  ...   NaN        S

[10 rows x 11 columns]

In [ ]:
X_teste.head(10)

PassengerId  Pclass  ... Cabin Embarked
360         1252       3  ...   NaN        S
170         1062       3  ...   NaN        S
224         1116       1  ...   NaN        C
358         1250       3  ...   NaN        Q
309         1201       3  ...   NaN        S
308         1200       1  ...   B69        S
150         1042       1  ...   C54        C
10           902       3  ...   NaN        S
21           913       3  ...   NaN        S
261         1153       3  ...   NaN        S

[10 rows x 11 columns]

In [ ]:
numericos_treino =X_treino[["PassengerId","Pclass","Age","SibSp","Parch","Fare"]]
numericos_teste =X_teste[["PassengerId","Pclass","Age","SibSp","Parch","Fare"]]

In [ ]:
numericos_treino.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
96           988       1  76.0      1    0.0  78.8500
381         1273       3  26.0      0    0.0   7.8792
89           981       2   2.0      1    1.0  23.0000
233         1125       3  28.0      0    0.0   7.8792
191         1083       1  28.0      0    0.0  26.0000

In [ ]:
numericos_teste.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
360         1252       3  14.5      8    2.0  69.5500
170         1062       3  28.0      0    0.0   7.5500
224         1116       1  53.0      0    0.0  27.4458
358         1250       3  28.0      0    0.0   7.7500
309         1201       3  45.0      1    0.0  14.1083

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

In [ ]:
imputer.fit(numericos_treino)

SimpleImputer()

In [ ]:
imputer.statistics_

array([1.10283904e+03, 2.29794521e+00, 3.00122603e+01, 4.07534247e-01,
       3.73287671e-01, 3.18367301e+01])

In [ ]:
numericos_treino = imputer.transform(numericos_treino)
numericos_teste =imputer.transform(numericos_teste)

In [ ]:
numericos_treino

array([[9.8800e+02, 1.0000e+00, 7.6000e+01, 1.0000e+00, 0.0000e+00,
        7.8850e+01],
       [1.2730e+03, 3.0000e+00, 2.6000e+01, 0.0000e+00, 0.0000e+00,
        7.8792e+00],
       [9.8100e+02, 2.0000e+00, 2.0000e+00, 1.0000e+00, 1.0000e+00,
        2.3000e+01],
       ...,
       [1.0090e+03, 3.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.6700e+01],
       [9.3900e+02, 3.0000e+00, 2.8000e+01, 0.0000e+00, 0.0000e+00,
        7.7500e+00],
       [1.0640e+03, 3.0000e+00, 2.3000e+01, 1.0000e+00, 0.0000e+00,
        1.3900e+01]])

In [ ]:
numericos_treino = pd.DataFrame(numericos_treino,columns=["PassengerId","Pclass","Age","SibSp","Parch","Fare"])
numericos_teste = pd.DataFrame(numericos_teste,columns=["PassengerId","Pclass","Age","SibSp","Parch","Fare"])

In [ ]:
numericos_treino.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0        988.0     1.0  76.0    1.0    0.0  78.8500
1       1273.0     3.0  26.0    0.0    0.0   7.8792
2        981.0     2.0   2.0    1.0    1.0  23.0000
3       1125.0     3.0  28.0    0.0    0.0   7.8792
4       1083.0     1.0  28.0    0.0    0.0  26.0000

In [ ]:
numericos_teste.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0       1252.0     3.0  14.5    8.0    2.0  69.5500
1       1062.0     3.0  28.0    0.0    0.0   7.5500
2       1116.0     1.0  53.0    0.0    0.0  27.4458
3       1250.0     3.0  28.0    0.0    0.0   7.7500
4       1201.0     3.0  45.0    1.0    0.0  14.1083

In [ ]:
numericos_treino.isnull().mean()

PassengerId    0.0
Pclass         0.0
Age            0.0
SibSp          0.0
Parch          0.0
Fare           0.0
dtype: float64

In [ ]:
numericos_teste.isnull().mean()

PassengerId    0.0
Pclass         0.0
Age            0.0
SibSp          0.0
Parch          0.0
Fare           0.0
dtype: float64

In [ ]:
numericos_treino =X_treino[["PassengerId","Pclass","Age","SibSp","Parch","Fare"]]
numericos_teste =X_teste[["PassengerId","Pclass","Age","SibSp","Parch","Fare"]]

In [ ]:
numericos_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Age            0.191781
SibSp          0.000000
Parch          0.123288
Fare           0.003425
dtype: float64

In [ ]:
numericos_teste.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Age            0.238095
SibSp          0.000000
Parch          0.095238
Fare           0.000000
dtype: float64

In [ ]:
imputer = SimpleImputer(strategy="median")

In [ ]:
imputer.fit(numericos_treino)

SimpleImputer(strategy='median')

In [ ]:
numericos_treino = imputer.transform(numericos_treino)
numericos_teste = imputer.transform(numericos_teste)

In [ ]:
numericos_treino

array([[9.8800e+02, 1.0000e+00, 7.6000e+01, 1.0000e+00, 0.0000e+00,
        7.8850e+01],
       [1.2730e+03, 3.0000e+00, 2.6000e+01, 0.0000e+00, 0.0000e+00,
        7.8792e+00],
       [9.8100e+02, 2.0000e+00, 2.0000e+00, 1.0000e+00, 1.0000e+00,
        2.3000e+01],
       ...,
       [1.0090e+03, 3.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.6700e+01],
       [9.3900e+02, 3.0000e+00, 2.8000e+01, 0.0000e+00, 0.0000e+00,
        7.7500e+00],
       [1.0640e+03, 3.0000e+00, 2.3000e+01, 1.0000e+00, 0.0000e+00,
        1.3900e+01]])

In [ ]:
numericos_teste

array([[1.252000e+03, 3.000000e+00, 1.450000e+01, 8.000000e+00,
        2.000000e+00, 6.955000e+01],
       [1.062000e+03, 3.000000e+00, 2.800000e+01, 0.000000e+00,
        0.000000e+00, 7.550000e+00],
       [1.116000e+03, 1.000000e+00, 5.300000e+01, 0.000000e+00,
        0.000000e+00, 2.744580e+01],
       [1.250000e+03, 3.000000e+00, 2.800000e+01, 0.000000e+00,
        0.000000e+00, 7.750000e+00],
       [1.201000e+03, 3.000000e+00, 4.500000e+01, 1.000000e+00,
        0.000000e+00, 1.410830e+01],
       [1.200000e+03, 1.000000e+00, 5.500000e+01, 1.000000e+00,
        1.000000e+00, 9.350000e+01],
       [1.042000e+03, 1.000000e+00, 2.300000e+01, 0.000000e+00,
        1.000000e+00, 8.315830e+01],
       [9.020000e+02, 3.000000e+00, 2.800000e+01, 0.000000e+00,
        0.000000e+00, 7.895800e+00],
       [9.130000e+02, 3.000000e+00, 9.000000e+00, 0.000000e+00,
        1.000000e+00, 3.170800e+00],
       [1.153000e+03, 3.000000e+00, 2.100000e+01, 0.000000e+00,
        0.000000e+00, 7.854

In [ ]:
!pip install feature-engine

In [ ]:
from feature_engine.imputation import MeanMedianImputer

In [ ]:
X_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.051370
Age            0.191781
SibSp          0.000000
Parch          0.123288
Ticket         0.000000
Fare           0.003425
Cabin          0.791096
Embarked       0.000000
dtype: float64

In [ ]:
X_teste.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.063492
Age            0.238095
SibSp          0.000000
Parch          0.095238
Ticket         0.000000
Fare           0.000000
Cabin          0.761905
Embarked       0.000000
dtype: float64

In [ ]:
X_treino.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
mediana_imputer = MeanMedianImputer(imputation_method="median",variables=["PassengerId","Pclass","Age","SibSp","Parch","Fare"])

In [ ]:
mediana_imputer.fit(X_treino)

MeanMedianImputer(variables=['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch',
                             'Fare'])

In [ ]:
mediana_imputer.imputer_dict_

{'Age': 28.0,
 'Fare': 13.8583,
 'Parch': 0.0,
 'PassengerId': 1101.5,
 'Pclass': 3.0,
 'SibSp': 0.0}

In [ ]:
X_treino = mediana_imputer.transform(X_treino)
X_teste = mediana_imputer.transform(X_teste)

In [ ]:
X_treino.head()

PassengerId  Pclass  ... Cabin Embarked
96           988       1  ...   C46        S
381         1273       3  ...   NaN        Q
89           981       2  ...   NaN        S
233         1125       3  ...   NaN        Q
191         1083       1  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
X_teste.head()

PassengerId  Pclass  ... Cabin Embarked
360         1252       3  ...   NaN        S
170         1062       3  ...   NaN        S
224         1116       1  ...   NaN        C
358         1250       3  ...   NaN        Q
309         1201       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
X_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.051370
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.791096
Embarked       0.000000
dtype: float64

In [ ]:
X_teste.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.063492
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.761905
Embarked       0.000000
dtype: float64

In [ ]:
imputer.imputer_dict_

AttributeError: ignored

In [ ]:
imputer_mediana = MeanMedianImputer(imputation_method="median",variables = ["PassengerId","Pclass","Parch","Age","SibSp","Fare"])

In [ ]:
imputer_mediana.fit(X_treino)

MeanMedianImputer(variables=['PassengerId', 'Pclass', 'Parch', 'Age', 'SibSp',
                             'Fare'])

In [ ]:
imputer_mediana.imputer_dict_

{'Age': 28.0,
 'Fare': 13.8583,
 'Parch': 0.0,
 'PassengerId': 1101.5,
 'Pclass': 3.0,
 'SibSp': 0.0}

In [ ]:
X_treino = imputer_mediana.transform(X_treino)
X_teste = imputer_mediana.transform(X_teste)

In [ ]:
X_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.051370
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.791096
Embarked       0.000000
dtype: float64

In [ ]:
X_teste.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.063492
Age            0.000000
SibSp          0.000000
Parch          0.095238
Ticket         0.000000
Fare           0.000000
Cabin          0.761905
Embarked       0.000000
dtype: float64

In [ ]:
X_treino.dtypes

PassengerId      int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch          float64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
X_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.051370
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.791096
Embarked       0.000000
dtype: float64

In [ ]:
X_treino["Sex"].unique()

array(['female', 'male', nan], dtype=object)

In [ ]:
X_teste["Sex"].unique()

array(['male', 'female', nan], dtype=object)

In [ ]:
sex_treino = X_treino["Sex"]
sex_teste = X_teste["Sex"]

In [ ]:
sex_treino.head()

96     female
381      male
89       male
233      male
191       NaN
Name: Sex, dtype: object

In [ ]:
sex_teste.head()

360      male
170      male
224    female
358      male
309    female
Name: Sex, dtype: object

In [ ]:
imputer_freq = SimpleImputer(strategy="most_frequent")

In [ ]:
imputer_freq.fit(sex_treino.to_frame())

SimpleImputer(strategy='most_frequent')

In [ ]:
imputer_freq.statistics_

array(['male'], dtype=object)

In [ ]:
sex_treino = imputer_freq.transform(sex_treino.to_frame())
sex_teste = imputer_freq.transform(sex_teste.to_frame())

In [ ]:
sex_treino =pd.DataFrame(sex_treino,columns=["Sex"])
sex_teste =pd.DataFrame(sex_teste,columns=["Sex"])

In [ ]:
sex_treino.head()

Sex
0  female
1    male
2    male
3    male
4    male

In [ ]:
sex_teste.head()

Sex
0    male
1    male
2  female
3    male
4  female

In [ ]:
from feature_engine.imputation import CategoricalImputer

In [ ]:
X_treino.isnull().mean()

PassengerId    0.000000
Pclass         0.000000
Name           0.000000
Sex            0.051370
Age            0.000000
SibSp          0.000000
Parch          0.123288
Ticket         0.000000
Fare           0.000000
Cabin          0.791096
Embarked       0.000000
dtype: float64

In [ ]:
X_treino.drop(columns=["Cabin"],inplace=True)
X_teste.drop(columns=["Cabin"],inplace=True)

In [ ]:
ft_imputer = CategoricalImputer(imputation_method="frequent",variables=["Sex"])

In [ ]:
ft_imputer.fit(X_treino)

CategoricalImputer(imputation_method='frequent', variables=['Sex'])

In [ ]:
ft_imputer.imputer_dict_

{'Sex': 'male'}

In [ ]:
X_treino = ft_imputer.transform(X_treino)
X_teste= ft_imputer.transform(X_teste)

In [ ]:
X_treino.head()

PassengerId  Pclass  ...     Fare Embarked
96           988       1  ...  78.8500        S
381         1273       3  ...   7.8792        Q
89           981       2  ...  23.0000        S
233         1125       3  ...   7.8792        Q
191         1083       1  ...  26.0000        S

[5 rows x 10 columns]

In [ ]:
X_teste.head()

PassengerId  Pclass  ...     Fare Embarked
360         1252       3  ...  69.5500        S
170         1062       3  ...   7.5500        S
224         1116       1  ...  27.4458        C
358         1250       3  ...   7.7500        Q
309         1201       3  ...  14.1083        S

[5 rows x 10 columns]

In [ ]:
X_treino.isnull().mean()

PassengerId    0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64

In [ ]:
X_teste.isnull().mean()

PassengerId    0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Embarked       0.0
dtype: float64