# Trabalhando com valores numéricos

In [ ]:

import pandas as pd

nome =["Miguel","Arthur","Heitor","Helena","Alice","Theo","Davi","Lilia","Laura","Gabriel","Bernardo","Samuel","Valentina","Heloísa","Enzo","Pedro" ,"Lorenzo","Sophia","Maria","Eduarda","Cecília","Júlia","Isabella","Benício"]
idade =[75,42,50,61,77,35,84,31,84,64,54,67,69,22,63,82,51,63,56,87,32,65,54,53]
saldo = [9734.05,12517.09,6304.24,11118.21,9542.27,2964.03,13232.54,11684.21,4919.49,5293.05,8847.02,1789.03,11113.87,11665.19,2432.18,11626.03,10038.05,1690.01,6409.31,13546.88,1298.90,1200.00,16000.00,5000.00]
dataframe = pd.DataFrame({"nome":nome,"idade":idade,"saldo":saldo})

In [ ]:
dataframe.head(10)

In [ ]:
bins = 4
largura = (maximo-minimo)/bins

In [ ]:
intervalos = [i for i in range(minimo,maximo+largura,largura)]

In [ ]:
intervalos = [i for i in range(minimo,maximo+largura,largura)]

In [ ]:
minimo = int(np.ceil(dataframe["saldo"].min()))
maximo = int(np.floor(dataframe["saldo"].max()))
largura = int((maximo-minimo)/4)

In [ ]:
dataframe["saldo_discretizado"] = pd.cut(dataframe["saldo"],bins=intervalos,include_lowest=True)

In [ ]:
dataframe.head()

In [ ]:
def disc_intervalo(dataframe,variavel,bins):
    maximo = int(np.floor(dataframe[variavel].max()))
    minimo = int(np.ceil(dataframe[variavel].min()))
    largura = int((maximo-minimo)/bins)


    intervalos = [i for i in range(minimo,maximo+largura,largura)]
    intervalos = intervalos[0:len(intervalos)-1]
    intervalo_discretizado = pd.cut(dataframe[variavel],bins=intervalos, include_lowest=True)


    return intervalo_discretizado

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

dataframe.groupby("saldo_discretizado")["saldo"].count().plot.bar()
plt.xticks(rotation=45)
plt.ylabel('Número de observações em cada intervalo')

In [ ]:
import pandas as pd

nome =["Miguel","Arthur","Heitor","Helena","Alice","Theo","Davi","Lilia","Laura","Gabriel","Bernardo","Samuel","Valentina","Heloísa","Enzo","Pedro" ,"Lorenzo","Sophia","Maria","Eduarda","Cecília","Júlia","Isabella","Benício"]
idade =[75,42,50,61,77,35,84,31,84,64,54,67,69,22,63,82,51,63,56,87,32,65,54,53]
saldo = [9734.05,12517.09,6304.24,11118.21,9542.27,2964.03,13232.54,11684.21,4919.49,5293.05,8847.02,1789.03,11113.87,11665.19,2432.18,11626.03,10038.05,1690.01,6409.31,13546.88,1298.90,1200.00,16000.00,5000.00]

dataframe = pd.DataFrame({"nome":nome,"idade":idade,"saldo":saldo})

In [ ]:
dataframe["saldo_discretizado"], intervalos = pd.qcut(dataframe["saldo"],4, labels=None,retbins=True)

In [ ]:
dataframe.head()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(12,7))
dataframe.groupby("saldo_discretizado")["idade"].count().plot.bar()
plt.xticks(rotation=45)
plt.ylabel('Número de observações em cada intervalo pelo método de frequência igual')

In [ ]:
def disc_freq(dataframe, variavel,q):
		maximo = dataframe[variavel].max()
		minimo = dataframe[variavel].min()
		
		largura = int((maximo-minimo)/bins)
		intervalos = [i for i in range(minimo,maximo+largura,largura)]
		discretizado,intervaldisc = pd.qcut(dataframe[variavel],q,labels=None,retbins=True)
                 
		
		return discretizado, intervaldisc

In [ ]:
import pandas as pd

nome =["Miguel","Arthur","Heitor","Helena","Alice","Theo","Davi","Lilia","Laura","Gabriel","Bernardo","Samuel","Valentina","Heloísa","Enzo","Pedro" ,"Lorenzo","Sophia","Maria","Eduarda","Cecília","Júlia","Isabella","Benício"]
idade =[75,42,50,61,77,35,84,31,84,64,54,67,69,22,63,82,51,63,56,87,32,65,54,53]
saldo = [9734.05,12517.09,6304.24,11118.21,9542.27,2964.03,13232.54,11684.21,4919.49,5293.05,8847.02,1789.03,11113.87,11665.19,2432.18,11626.03,10038.05,1690.01,6409.31,13546.88,1298.90,1200.00,16000.00,5000.00]

dataframe = pd.DataFrame({"nome":nome,"idade":idade,"saldo":saldo})

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
discretizador = KBinsDiscretizer(n_bins=8,encode="ordinal",strategy="kmeans")

In [ ]:
discretizador.fit(dataframe["saldo"].to_frame())

In [ ]:
dataframe["saldo_discretizado"] = discretizador.transform(dataframe["saldo"].to_frame())

dataframe.head()

In [ ]:
discretizador.bin_edges_

array([array([22.,27.5,37.5,46.83333333,55.08333333,
	61.625,70.375,80.3,87.])],dtype=object)

In [ ]:
dataframe.head()

In [ ]:
from sklearn.tree import DecisionTreeRegressor

arvore = DecisionTreeRegressor(max_depth=3, random_state=0)

In [ ]:
arvore.fit(dataframe["idade"].to_frame(),dataframe["saldo"])

In [ ]:
dataframe["idade_discretizada"] = arvore.predict(dataframe["idade"].to_frame)

In [ ]:
dataframe.head()

In [ ]:
dataframe.groupby("idade_discretizada")["saldo"].mean().plot()
plt.title("Relação mônotonica entre as variáveis idade_discretizada e saldo")
plt.ylabel("Saldo")

In [ ]:
import pandas as pd

nome =["Miguel","Arthur","Heitor","Helena","Alice","Theo","Davi","Lilia","Laura","Gabriel","Bernardo","Samuel","Valentina","Heloísa","Enzo","Pedro" ,"Lorenzo","Sophia","Maria","Eduarda","Cecília","Júlia","Isabella","Benício"]
idade = [75,42,50,61,77,35,84,31,84,64,54,67,69,22,63,82,51,63,56,87,32,65,54,53]
saldo = [9734.05,12517.09,6304.24,11118.21,9542.27,2964.03,13232.54,11684.21,4919.49,5293.05,8847.02,1789.03,11113.87,11665.19,2432.18,11626.03,10038.05,1690.01,6409.31,13546.88,1298.90,1200.00,16000.00,5000.00]

dataframe= pd.DataFrame({"nome":nome,"idade":idade,"saldo":saldo})

In [ ]:
plt.figure(figsize=(12,7))
dataframe.groupby("saldo")["idade"].mean().plot()
plt.title("Relação não monotônica entre a variável saldo e a idade")
plt.ylabel("Idade")

In [ ]:
from feature_engine.discretisation import DecisionTreeDiscretiser

In [ ]:
arvore_ft = DecisionTreeDiscretiser(cv=10,param_grid={"max_depth":[1,2]})

In [ ]:
arvore_ft.fit(dataframe["saldo"].to_frame(),dataframe["idade"])

In [ ]:
dataframe["saldo_discretizado"] = arvore.predict(dataframe["saldo"].to_frame())

In [ ]:
dataframe["saldo_discretizado"].unique()

In [ ]:
dataframe["idade_discretizada"].unique()

array([4096.13157895,6663.11])

# Projeto Prático

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(dataframe.drop("Survived",axis=1),dataframe["Survived"],test_size=0.3,random_state=0)


In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:

discretizador = KBinsDiscretizer(n_bins=8,encode="ordinal",strategy="uniform")

In [ ]:
discretizador.fit(X_treino[["Age","Fare"]])

In [ ]:
discretizador.fit(X_treino[["Age","Fare"]])
KBinsDiscretizer(encode='ordinal',n_bins=8,strategy='uniform')

In [ ]:
discretizador.bin_edges_


In [ ]:
array([array(0.17,9.64875,19.1275,28.60625,38.085,47.56375,
       57.0425,66.52125,76.]),
       array([0.,64.04115,128.0823,192.12345,256.16.46,320,20575,
       384.2469,448,28805,512.3292])], dtype=object)

In [ ]:

treino_disc= discretizador.transform(X_treino)
teste_disc= discretizador.transform(X_teste)

In [ ]:

treino_disc = pd.DataFrame(treino_disc,columns=["Age","Fare"])
teste_disc = pd.DataFrame(teste_disc,columns=["Age","Fare"])

In [ ]:
df1 = treino_disc['Age'].value_counts() / len(treino_disc)
df2 = teste_disc['Age'].value_counts() / len(teste_disc)

In [ ]:
aux = pd.concat([df1, df2], axis=1)

In [ ]:
aux.columns = ['treino','teste']

In [ ]:
aux.plot.bar()
plt.xticks(rotation=45)
plt.ylabel('Número de observações por intervalos')

In [ ]:
from feature_engine.discretisation import EqualWidthDiscretiser

In [ ]:
discretizador_ft = EqualWidthDiscretiser(bins=8, variables=["Age","Fare"])

In [ ]:
discretizador_ft.fit(X_treino)

In [ ]:
df_treino = discretizador_ft.transform(X_treino)
df_teste = discretizador_ft.transform(X_teste)

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(dataframe.drop("Survived",axis=1),dataframe["Survived"],test_size=0.3,random_state=0)

In [ ]:
discretizador_freq = KBinsDiscretizer(n_bins=4, encode="ordinal",strategy="quantile)

In [ ]:
discretizador_freq = KBinsDiscretizer(n_bins=4, encode="ordinal",strategy="quantile)

In [ ]:
discretizador_freq.fit(X_treino)[["Age","Fare"]]

In [ ]:
discretizador_freq.bin_edges_

In [ ]:
treino_freq = discretizador_freq.transform(X_treino[["Age","Fare"]])
teste_freq = discretizador_freq.transform(X_teste[["Age","Fare"]])

treino_freq = pd.DataFrame(treino_freq,columns=["Age","Fare"])
teste_freq = pd.DataFrame(teste_freq,columns=["Age","Fare"])

In [ ]:
def compara_proporcao(dataframe1,dataframe2)
    prop1 = dataframe1.value_counts() / len(dataframe1)
    prop2 = dataframe2.value_counts() / len(dataframe2)

    aux = pd.concat([prop1, prop2], axis=1)
    plt.figure(figsize=(12,9))
    aux.columns = ['treino', 'teste']
    aux.plot.bar()
    plt.xticks(rotation=45)
    plt.ylabel('Número de observações por intervalos')

In [ ]:
compara_proporcao(treino_freq["Age"],teste_freq["Age"])

In [ ]:
compara_proporcao(treino_freq["Fare"],teste_freq["Fare"])

In [ ]:
from feature_engine.discretisers import EqualFrequencyDiscretiser

In [ ]:
discretizador_ft = EqualFrequencyDiscretiser(q=10,variables=["Age","Fare"])
discretizador_ft.fit(X_treino)

In [ ]:
discretizador_ft.binner_dict_

In [ ]:
treino_ft = discretizador_ft.transform(X_treino)
teste_ft =discretizador_ft.transform(X_teste)

In [ ]:
treino_ft.head()

In [ ]:
teste_ft.head()

In [ ]:
compara_propocao(treino_ft["Age"],teste_ft["Age"])

In [ ]:
compara_proporcao(treino_ft["Fare"],teste_ft["Fare"])

In [ ]:
from sklearn.model_selection import train_test_split


X_treino, X_teste, y_treino, y_teste = train_test_split(dataframe.drop("Survived",axis=1),dataframe["Survived"],test_size=0.3,random_state=0)

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
discretizador = KBinsDiscretizer(n_bins=4,encode="ordinal",strategy="kmeans")

In [ ]:
discretizador.fit(X_treino[["Age","Fare"]])

In [ ]:
treino_discretizado = discretizador.transform(X_treino[["Age","Fare"]])
teste_discretizado = discretizador.transform(X_teste[["Age","Fare"]])

In [ ]:
treino_discretizado = pd.DataFrame(treino_discretizado,columns=["Age","Fare"])
teste_discretizado = pd.DataFrame(teste_discretizado,columns=["Age","Fare"])

In [ ]:
treino_discretizado.head()

In [ ]:
teste_discretizado.head()

In [ ]:
discretizador.bin_edges_

array([array([0.17,19.25741499,34.13871001,50.41116942,76.]),
       array([0.,44.34356705,151.61194821,370.89877, 512.392])],dtype =object)

In [ ]:
discretizador.n_bins_

In [ ]:
dataframe = pd.read_csv("train.csv")
dataframe.head()

In [ ]:
plt.figure(figsize=(12,7))
dataframe.groupby("SQUARE_FT")["TARGET\(PRICE_IN_LACS)"].mean().plot()
plt.title("Relação  entre a variável SQUARE_FT e TARGET\(PRICE_IN_LACS)")
plt.ylabel("Média dos preços")

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(dataframe.drop("TARGET\(PRICE_IN_LACS)",axis=1),dataframe["TARGET\(PRICE_IN_LACS)"],test_size=0.3,random_state=0)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

arvore = DecisionTreeRegressor(max_depth=4, random_state=0)

In [ ]:
arvore.fit(X_treino["SQUARE_FT"].to_frame(),y_treino)

In [ ]:
square_treino = arvore.predict(X_treino["SQUARE_FT"].to_frame())
square_teste = arvora.predict(X_teste["SQUARE_FT"].to_frame())

In [ ]:
from feature_engine.discretisation import DecisionTreeDiscretiser

arvore_ft = DecisionTreeDiscretiser(variables=['Age', 'Fare'],regression=True, param_grid={'max_depth': [1,2,3,4]})

In [ ]:

arvore_ft.fit(X_treino,y_treino)

In [ ]:
treino_disc = arvore_ft.transform(X_treino)
teste_disc = arvore_ft.transform(X_teste)

In [ ]:
teste_disc.benner_dict_